### ISSUE TITLE
error loading plugin?

### ISSUE THREAD

**Issue by HarHarLinks** [maubot/sed#10]
[xyz.maubot.sed-master-e1934b6f.mbp](https://mau.dev/maubot/sed/-/jobs/4873/artifacts/file/xyz.maubot.sed-master-e1934b6f.mbp) with dock.mau.dev/maubot/maubot:latest (== 0.2.1)
```
maubot    | [2022-01-24 13:02:56,827] [ERROR@maubot.server] Error in handler
maubot    | Traceback (most recent call last):
maubot    |   File "/opt/maubot/maubot/management/api/middleware.py", line 49, in error
maubot    |     return await handler(request)
maubot    |   File "/opt/maubot/maubot/management/api/plugin_upload.py", line 60, in upload_plugin
maubot    |     return await upload_new_plugin(content, pid, version)
maubot    |   File "/opt/maubot/maubot/management/api/plugin_upload.py", line 78, in upload_new_plugin
maubot    |     return resp.created(plugin.to_dict())
maubot    |   File "/opt/maubot/maubot/loader/zip.py", line 87, in to_dict
maubot    |     **super().to_dict(),
maubot    |   File "/opt/maubot/maubot/loader/abc.py", line 106, in to_dict
maubot    |     "id": self.meta.id,
maubot    | AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by HarHarLinks** [comment]
well i restarted the maubot container and it started to not error?
