### ISSUE TITLE
support e2ee

### ISSUE THREAD

**Issue by HarHarLinks** [maubot/sed#9]
It seems encryption is not properly implemented for this plugin. I'm running the :latest docker container from dock.mau.dev and set up e2ee as explained in the docs. e2ee is working in principle since commands are triggered, but sed needs to read another, replied-to, event which does not get properly decrypted first as it seems:

```
Failed to run handler
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/client/syncer.py", line 200, in _catch_errors
    await handler(data)
  File "/data/plugins/xyz.maubot.sed-v1.0.0-ts1623072145.mbp/sed.py", line 174, in message_handler
    await self.command_handler(evt)
  File "/opt/maubot/maubot/handlers/command.py", line 395, in replacement
    await asyncio.gather(combine(self, evt), orig_replacement(self, evt))
  File "/opt/maubot/maubot/handlers/command.py", line 385, in replacement
    await func(self, evt, val)
  File "/data/plugins/xyz.maubot.sed-v1.0.0-ts1623072145.mbp/sed.py", line 198, in command_handler
    await self._try_replace_event(evt.event_id, stmt, reply_evt)
  File "/data/plugins/xyz.maubot.sed-v1.0.0-ts1623072145.mbp/sed.py", line 148, in _try_replace_event
    replaced = self._exec(stmt, orig_evt.content.body)
AttributeError: 'EncryptedMegolmEventContent' object has no attribute 'body'
```

**Comment by tulir** [comment]
Plugins generally never deal with encryption, maubot/maubot#123
